clone:
  depth: 1
kind: pipeline
name : NexusKernel
steps:
 - name: MSM8953
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - /noclone3 bash build.sh
